<?php

namespace AppBundle\Repository;

/**
 * RobotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RobotRepository extends \Doctrine\ORM\EntityRepository
{
}
